config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
     get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about'
  resources :posts

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable,:confirmable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]


  def index
   @post = Post.all
  end

  def new
     @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
end

def edit
  @post = Post.find(params[:id])
end

def update
  @post = Post.find(params[:id])

  if (@post.update(post_params))
   redirect_to @post
 else
   render 'edit'
 end
end

 def destroy
   @post = Post.find(params[:id])
@post.destroy
redirect_to post_path
end

  def create
  #render plain: params[:post].inspect
   @post = Post.new(post_params)


  if (@post.save)
   redirect_to @post
 else
   render 'new'
 end
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

  </head>

  <body>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0  font-weight-normal">KAKA;)</h5>
      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <span class="me-3 py-2 text-dark text-decoration-none" ><%= link_to "Главнвя страница", home_path %></span>
        <% if user_signed_in? %>
          <span class="me-3 py-2 text-dark text-decoration-none" ><%= link_to "Виход",destroy_user_session_path, method: :delete  %></span>
        <% else %>
      <span class="me-3 py-2 text-dark text-decoration-none" ><%= link_to "Вход",new_user_session_path  %></span>
<span class="me-3 py-2 text-dark text-decoration-none" ><%= link_to "Регистрация",new_user_registration_path  %></span>
<% end %>
      </nav>

      <span  class=" btn btn-primary ><%= link_to "Добавление статьи", new_post_path %></span>

    </div>
<div class='container'>

<%= yield %>
</div>
  </body>
</html>